import Head from 'next/head';
import RenderPlayer from '../Components/Player';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <RenderPlayer color={'#b46f6f'} />
        </div>
      </main>
    </>
  );
}
